[workspace]
members = [
    "programs/*",
    "tests"
]
resolver = "2"

[profile.release]
opt-level = "z"
lto = "thin"
codegen-units = 1
panic = "abort"
overflow-checks = true
incremental = true

[profile.release.build-override]
opt-level = 3
incremental = true
codegen-units = 1
